import { Bullets, Callout, Code, PageHeader, Section, Steps, SubSection, Table, Term } from "../_components/doc"

export const metadata = { title: "Handbook — Search & SEO" }

/**
 * The runbook for getting CrossFriend into Google and the AI answer engines.
 *
 * Written so someone who has never touched SEO can follow it end to end without asking anyone. Two
 * rules kept throughout: every artefact is given as a URL you can open right now to check it
 * yourself, and every step says what "correct" looks like — a runbook that only lists actions
 * leaves you unable to tell whether the action worked.
 */
export default function HelpSeoPage() {
  return (
    <>
      <PageHeader
        title="Search & SEO"
        intro="Where the search artefacts live, how to check them, and the exact steps to get CrossFriend indexed by Google and quoted by AI answer engines. Nothing here needs a developer."
      />

      <Section title="The artefacts, and where to find them">
        <p>
          These are generated by the storefront from live data. There are no files to upload
          anywhere — they are already being served. Open any of them in a browser to check them.
        </p>
        <Table
          head={["Artefact", "URL", "What it does", "Looks right when"]}
          rows={[
            [
              <strong key="a">Sitemap</strong>,
              <Term key="b">crossfriend.in/sitemap.xml</Term>,
              "Lists every page we want Google to know about",
              "It contains product, baker and occasion URLs — not just the ~13 fixed pages",
            ],
            [
              <strong key="c">Robots file</strong>,
              <Term key="d">crossfriend.in/robots.txt</Term>,
              "Tells crawlers what they may read, and points at the sitemap",
              <span key="e">
                The last line reads <Term>Sitemap: https://crossfriend.in/sitemap.xml</Term>
              </span>,
            ],
            [
              <strong key="f">Canonical tag</strong>,
              "In the HTML of every page",
              "Tells Google the one true address of a page",
              <span key="g">
                It starts <Term>https://crossfriend.in</Term> — never <Term>localhost</Term>
              </span>,
            ],
            [
              <strong key="h">Structured data</strong>,
              "In the HTML of every page",
              "Machine-readable facts — price, FAQ, business details. This is what AI answers quote",
              "Google's Rich Results Test reports no errors",
            ],
          ]}
        />

        <SubSection title="How to check them yourself">
          <p>Open these in any browser. No login, no tools.</p>
          <Code>{`https://crossfriend.in/sitemap.xml
https://crossfriend.in/robots.txt`}</Code>
          <p>
            For the canonical tag and structured data, paste a page URL into Google&apos;s own
            checkers — both are free and need no account:
          </p>
          <Bullets
            items={[
              <span key="a">
                <strong>Rich Results Test</strong> — search.google.com/test/rich-results. Paste any
                page URL. It shows the structured data Google can read.
              </span>,
              <span key="b">
                <strong>Schema Markup Validator</strong> — validator.schema.org. Stricter, catches
                things Google&apos;s tool ignores.
              </span>,
            ]}
          />
        </SubSection>

        <Callout tone="warn" title="Check the sitemap before you submit it">
          A sitemap that lists only the fixed pages and no products, bakers or occasions is broken —
          it means the storefront could not reach the backend when it was generated. It still looks
          like a valid file, so nothing else will warn you. If you submit a broken sitemap, Google
          caches it and you have to wait for it to re-read. Always open the URL and look before
          moving on.
        </Callout>
      </Section>

      <Section title="One-time setup — do this in order">
        <p>
          Roughly 30 minutes, once. Steps 1 and 2 need access to whoever controls the domain&apos;s
          DNS. Everything else is clicking.
        </p>

        <SubSection title="Step 1 — Google Search Console">
          <p>
            This is the single most important thing on the page. Without it we are invisible to
            ourselves: no way to know what Google has indexed, what it rejected, or why.
          </p>
          <Steps
            items={[
              <span key="a">
                Go to <Term>search.google.com/search-console</Term> and sign in with the company
                Google account — not a personal one.
              </span>,
              <span key="b">
                Click <strong>Add property</strong> and choose <strong>Domain</strong> (the left
                option), not URL prefix. Domain covers crossfriend.in, www, and every subdomain in
                one property.
              </span>,
              <span key="c">
                Enter <Term>crossfriend.in</Term>. Google gives you a TXT record.
              </span>,
              <span key="d">
                Add that TXT record at the domain registrar — the same place A records are managed.
                Then click <strong>Verify</strong>. If it fails, wait 15 minutes and retry; DNS takes
                time to propagate.
              </span>,
            ]}
          />
        </SubSection>

        <SubSection title="Step 2 — submit the sitemap">
          <Steps
            items={[
              <span key="a">
                Open <Term>crossfriend.in/sitemap.xml</Term> first and confirm it lists more than the
                fixed pages. Do not skip this.
              </span>,
              <span key="b">
                In Search Console, open <strong>Sitemaps</strong> in the left menu.
              </span>,
              <span key="c">
                Type just <Term>sitemap.xml</Term> in the box — not the full URL — and click{" "}
                <strong>Submit</strong>.
              </span>,
              <span key="d">
                Status should become <strong>Success</strong> within a few minutes, showing the
                number of URLs discovered.
              </span>,
            ]}
          />
        </SubSection>

        <SubSection title="Step 3 — force a re-crawl of the key pages">
          <p>
            Submitting a sitemap tells Google the pages exist. It does not make Google look at them
            promptly. This step does, and it matters most on a site Google has crawled before.
          </p>
          <Steps
            items={[
              <span key="a">
                In Search Console, paste a URL into the search bar at the top (this is{" "}
                <strong>URL Inspection</strong>).
              </span>,
              <span key="b">
                Click <strong>Request Indexing</strong>. It takes about a minute per URL.
              </span>,
              <span key="c">
                Do these five, in this order: the homepage, <Term>/ai-cake-studio</Term>,{" "}
                <Term>/store</Term>, <Term>/bakers</Term>, <Term>/cake-size-calculator</Term>.
              </span>,
            ]}
          />
          <Callout tone="info" title="There is a daily quota">
            Google limits how many URLs you can submit this way per day. Spend it on pages that
            matter — landing pages and tools, not legal pages. Legal pages will be found through the
            sitemap in their own time.
          </Callout>
        </SubSection>

        <SubSection title="Step 4 — Bing Webmaster Tools">
          <p>
            Worth fifteen minutes for a reason that is not obvious: <strong>Bing&apos;s index feeds
            ChatGPT and Microsoft Copilot</strong>. If we want to be quoted by AI assistants, Bing is
            the cheapest way in.
          </p>
          <Steps
            items={[
              <span key="a">
                Go to <Term>bing.com/webmasters</Term> and sign in.
              </span>,
              <span key="b">
                Choose <strong>Import from Google Search Console</strong>. It copies the property and
                the sitemap across automatically.
              </span>,
            ]}
          />
        </SubSection>

        <SubSection title="Step 5 — Google Business Profile">
          <p>
            At our current size the Business Profile outranks everything on the website for local
            searches like &quot;cake shop near me&quot;. Keep it current, and link it to Search
            Console from the profile settings so the two report together.
          </p>
        </SubSection>
      </Section>

      <Section title="After a storefront deploy">
        <p>
          Most deploys need nothing. Do this only when a deploy changed pages, added a page, or
          touched anything described on this page.
        </p>
        <Steps
          items={[
            <span key="a">
              Open <Term>crossfriend.in/sitemap.xml</Term>. Confirm the new page is listed and that
              product and baker URLs are still there.
            </span>,
            <span key="b">
              In Search Console, use <strong>URL Inspection</strong> → <strong>Request Indexing</strong>{" "}
              on any genuinely new page. No need to resubmit the sitemap — Google re-reads it on its
              own schedule.
            </span>,
          ]}
        />
      </Section>

      <Section title="Weekly check — five minutes">
        <p>Open Search Console once a week and look at three things.</p>
        <Table
          head={["Where", "What you are looking for", "Act when"]}
          rows={[
            [
              <strong key="a">Pages</strong>,
              "How many are indexed, and the reasons given for those that are not",
              "Indexed count drops, or a reason you have not seen before appears",
            ],
            [
              <strong key="b">Sitemaps</strong>,
              "Status still Success, discovered URL count still sensible",
              <span key="c">
                Status is <strong>Couldn&apos;t fetch</strong>, or the count falls sharply
              </span>,
            ],
            [
              <strong key="d">Performance</strong>,
              "Which search terms show us, and which get clicks",
              "Never urgent — this is where content ideas come from",
            ],
          ]}
        />
        <Callout tone="info" title="Expect nothing for a while">
          A new domain takes 4–8 weeks before search traffic means anything. Indexing takes days to
          two weeks. Numbers in the first fortnight are noise — do not act on them, and do not change
          things in response to them.
        </Callout>
      </Section>

      <Section title="When something looks wrong">
        <Table
          head={["Symptom", "Most likely cause", "What to do"]}
          rows={[
            [
              "Sitemap lists only ~13 pages",
              "The storefront could not reach the backend when the sitemap was generated",
              "Tell a developer. Do not submit it to Google in this state",
            ],
            [
              <span key="a">
                Canonical shows <Term>localhost</Term>
              </span>,
              "The site was built without the public address configured",
              "Tell a developer immediately — this stops the whole site being indexed",
            ],
            [
              <span key="b">
                Search Console says <strong>Discovered — currently not indexed</strong>
              </span>,
              "Normal on a new site. Google knows the page but has not prioritised it",
              "Request indexing on the important ones. Otherwise wait",
            ],
            [
              <span key="c">
                Search Console says <strong>Duplicate, Google chose different canonical</strong>
              </span>,
              "Two of our URLs serve the same content",
              "Note which pages, tell a developer",
            ],
            [
              <span key="d">
                <strong>Couldn&apos;t fetch</strong> on the sitemap
              </span>,
              "The site was down when Google tried, or the sitemap is erroring",
              <span key="e">
                Open <Term>crossfriend.in/sitemap.xml</Term> yourself. If it loads, click Resubmit
              </span>,
            ],
          ]}
        />
      </Section>

      <Section title="What none of this fixes">
        <Callout tone="warn" title="SEO gets us found. It does not give us something to find.">
          <p>
            Every step here makes an existing page discoverable. None of it creates pages. A
            correctly configured site with an empty catalogue ranks for nothing, because there is
            nothing to rank.
          </p>
          <p>
            The two things that actually move search results at this stage are{" "}
            <strong>more bakers listing real products</strong> and{" "}
            <strong>pages that answer questions nobody else can answer</strong> — our own pricing
            data, our own bakers, our own AI-generated designs. Both are operational work, not
            technical work.
          </p>
        </Callout>
      </Section>
    </>
  )
}
